### PR TITLE
fix(#2210) | Adds check for correct handler factory

### PR DESCRIPTION
**Pull request by DevJonny**
Fix for issue #2210.

Changes made:

1. Change language version to C# 9 on the `Paramore.Brighter.csproj`. I can't remember where we were at with language versions. If we're not happy to move to 9 I can change my code to work with 8, it just won't be as succint.

2. Adds a check in the `CommandProcessor` for making sure that the `handlerFactory` is either a `IAmAHandlerFactorySync` or a `IAmAHandlerFactoryAsync` and throws an exception with a sensible message if not. This is so when moving from Brighter 8.x -> 9.x you don't get tripped up by using `IAmAHandlerFactory`. See Issue #2210 for details.

3. Removed now redundant tests that checked for errors when a null handler factory is passed

### CODE REVIEW

**Review by iancooper — COMMENTED** [review]
So this is a good general fix - we definitely need to give a lot more feedback in configuration that lets you explicitly know what you misconfigured.

Up to now though we have not moved to C# 9 because it requires runtime support that is not in netstandard 2.0. Some language elements - those that don't need the language runtime work - but others don't

**Comment by iancooper** [comment]
@preardon @holytshirt Any thoughts on C#8 vs C#9. I think the language runtime support requirements make this a little bit hairy. Some C#9 features will work, other's won't. I'm inclined to stick with C#8 until we feel netstandard 2.0 is no longer required, but that feels like v10 not v9.X, if then? But think this is a majority call.

**Comment by preardon** [comment]
It's an interesting one for me, as we are requiring latest versions of all downstream packages.

Personally I like to maintain new lang versions, but maintaing framework compatibility is important given lots of people are still on it

**Comment by iancooper** [comment]
@preardon We should not upgrade to packages that don't support .netstandard2.0 without multi-targeting. That advice based on discussions we had with the DotNet team.

**Comment by preardon** [comment]
@iancooper completely agree

Was just worried that Lang ver upgrades might break framework support as well

**Comment by iancooper** [comment]
@preardon Yeah, that is the issue. To use C#9, we can only use a subset of the features--those that don't require runtime support. So we could use some parts, but not others. My concern is that this is harder to get right than a simple "don't"

In essence we can use 7.3 and 8 and above only with run-time support, see: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version

I believe that Mads says, use of nullable types is tested to work in 7.3 and recommended but not others.

BTW for samples, just use .NET 6 and latest language. The issue is just the libs

**Comment by iancooper** [comment]
BTW, for reference, if we leave netstandard2.0 for netstandard2.1 (we have had to for some libs where there is no maintained 2.0 support) we lose .NET framework 4.8 support and only have .NET Core 3.1 and above. It's difficult to know how much of our customer base uses .NET Framework 4.8. I think if we wanted to drop support it would be a major version change.

**Comment by DevJonny** [comment]
Thanks for the confirmation @iancooper / @preardon, I couldn't remember where we landed. 

I've reverted back to C# 8, and updated the check accordingly. Should be all good now.

**Comment by DevJonny** [comment]
Urggh I need to fix a bunch of tests now as they're passing in `IAmAHandlerFactory` instead of `IAmAHandlerFactory(A)sync`. I'll fix up.

**Comment by holytshirt** [comment]
> Urggh I need to fix a bunch of tests now as they're passing in `IAmAHandlerFactory` instead of `IAmAHandlerFactory(A)sync`. I'll fix up.

You mean tdd works ;)

**Comment by DevJonny** [comment]
Good news is a few tests needed removing (because they're checking the same thing, but at the point where the handler is created which is too late), I've still got a couple of failing tests I need to sort, but I'll do that tonight.

**Comment by DevJonny** [comment]
Build failed because it took over 30 minutes to run :(

**Review by holytshirt — APPROVED** [review]

**Pull request merged**
