### PR TITLE
Fix for SqsSubscription Constructor parameters incorrectly assigned issue

### PR DESCRIPTION
**Pull request by honkuan86**
Related Issue: #1516

### CODE REVIEW

**Review by iancooper — COMMENTED** [review]
Good spot, the reverse in parameter order from Subscription is a pain though. Maybe we should re-order these parameters on the SqsSubscription constructor to match the order on Subscription as well. That should be more comprehensible, as I suspect this problem occurred because  of the ordering not being the same here

**Comment by honkuan86** [comment]
> Good spot, the reverse in parameter order from Subscription is a pain though. Maybe we should re-order these parameters on the SqsSubscription constructor to match the order on Subscription as well. That should be more comprehensible, as I suspect this problem occurred because of the ordering not being the same here

Yup agreed on re-ordering the parameters. Should we consider those who already using this class ? If we re-order the parameters, the changes will be hard to notice, since both of these are int type, so they won't be notified from the compiler until they run the program.

**Comment by iancooper** [comment]
> Yup agreed on re-ordering the parameters. Should we consider those who already using this class ? If we re-order the parameters, the changes will be hard to notice, since both of these are int type, so they won't be notified from the compiler until they run the program.

The switch to the SqsSubscription class comes with v9, so only early adopters will be using, who should have taken it as "pre-release'. So I would rather change now, before we go to final, than leave it to later when we will have the problem you identify

**Review by iancooper — APPROVED** [review]

**Comment by iancooper** [comment]
Thanks for that. I'll merge

**Pull request merged**
