### PR TITLE
Update documentation for EFCore_WebApi example

### PR DESCRIPTION
**Pull request by omelianlevkovych**
# Description
Updated the documentation readme file for the example project.

## Reasoning behind the change
While doing onboarding I have faced few obstacles. 
It was considered that documentation update will be helpful. Therefore newcomers will not have to face same issues.

## Additional changes
I have added table of content and fixed some typos.

### CODE REVIEW

**Comment by omelianlevkovych** [comment]
Unfortunately, I haven't really used much github yet. In case I do need to link an issue somehow here, please, let me know.

Also I have a few additional questions.
* We do have docker-compose file in the example folder, however I failed to run it. What I am doing wrong, and what is the initial purpose of that file (we do have docker compose files in root folder already).
* In case it the docker compose file somehow can be used, can we add phpmyadmin as well. The GUI can be really helpful for folks who haven't used the MySQL a lot yet.
* We also have a build.sh file. Do we want powershell scrip as well for the Windows users. Is it even a forbidden question in the open source community :laughing: ? I am not sure whether it is possible to run build.sh script on Windows OS.

**Review by iancooper — APPROVED** [review]
These look really helpful

**Comment by iancooper** [comment]
>We do have docker-compose file in the example folder, however I failed to run it.
OK, I'll add it to my list of things to investigate, alongside the failing global inbox switch

>In case it the docker compose file somehow can be used, can we add phpmyadmin as well.
Not used that before - so something for me to investigate (I tend to use DataGrip)

>We also have a build.sh file. Do we want powershell scrip as well for the Windows users. 
We can, I am just on a Mac so it would be hard to test. Some of the other maintainers are on Windows machines though. We don't have a preference as to the OS :-D

**Review by preardon — APPROVED** [review]
Looks, good to me, thanks for putting the effort in :)

**Pull request merged**
