### PR TITLE
Reduce command processor ctor's

### PR DESCRIPTION
**Pull request by preardon**
@iancooper Here is a first go

One test failing, interesting one, it appears that when you "Mark Dispatched" if your producer supports Publish Confirmations it goes down that route weather its configured or not

### CODE REVIEW

**Comment by iancooper** [comment]
Looking at this I wonder if the answer is to go further.

We could treat IAmAn**** as a base 'marker' interface with no methods, and have explicit IAmAn***Sync and IAmAn***Async that derive from it. So IAmAnOutbox can have IAmAnOutboxSync and  IAmAnOutboxAsync.

Then the CommandProcessor constructor only ever takes the base IAmAn****, for example  IAmAnOutbox and we **always** query the interfaces that you support i.e. sync and async, thus removing any need to repeat the constructors for both types but supporting you supplying us an implementation that supports one or both.

That seems to give flexibility to everyone, the only thing it blocks is entirely separate codebases for sync and async but I think that edge case will be sufficiently unusual to not support it.

What do you think?

**Comment by preardon** [comment]
If we wanted to go down this path I see only two options, either do as you say to have a common Interface and then split sync and Async, or update all interfaces to contain both sync and Async.

I see using the common interface with both sync and Async ones as easiest

**Comment by preardon** [comment]
@iancooper There is 1 Failing test that I would like you to look at,

When_Posting_Via_A_Control_Bus_Sender_Async (ControlBusSenderPostMessageAsyncTests.cs)

No sure why it was working before, however the current logic states that if the Sync Message Producer is ISupportPublishConfirmation then don't mark as dispatched. I understand that for RPC we don't particularly want to mark as dispatched however this logic means that if our producer supports it (and we don't want to use RPC) that it all always want to go down this path

**Comment by iancooper** [comment]
@preardon Let me take a look, and see if I can figure out why that one is miserable

**Comment by iancooper** [comment]
@preardon Going to merge and review the test after, as that will be easier I think at this point. I think this is a significant step towards reducing the api complexity, so let's make progress with it.

**Pull request merged**
