### PR TITLE
CommandProcessor Bulk Clear #1764

### PR DESCRIPTION
**Pull request by preardon**
This should allow the Command Processor to Bulk Clear from the Outbox and send Messages to Transports in Batches

@iancooper I would appreciate you're thoughts on this when you have a second before I get too much deeper, however I understand that this is for v9.next

### CODE REVIEW

**Comment by iancooper** [comment]
This looks fairly solid and I don't have any issues with how this is working. We may want to make sure that a publisher confirm works with this, but that would mean we would need to update the transport for RMQ etc, and I am fine with doing that after you get ASB in

**Comment by preardon** [comment]
@iancooper thanks for this, I will continue down this path and get a PR in

**Comment by preardon** [comment]
This Adds the following Functionality

- Outbox - Get Multiple by ID
- Outbox Mark Multiple as Dispatched by ID
- Command Processor - Bulk Clear
- New Interface for Producers that support Bulk
- Outbox Sweeper - Ability to set to Use Bulk

@iancooper this should be a MVP to allow ASB to dispatch as Bulk, let me know what you think

**Review by iancooper — APPROVED** [review]
I think this works. What we might be able to look at is the same model we use elsewhere - launch a thread to run the bulk update and use a mutex to prevent re-entry if a bulk clear is already running. But I can point you in the direction of our prior art there.

**Pull request merged**
