### PR TITLE
Make RawMessageDelivery option configurable

### PR DESCRIPTION
**Pull request by honkuan86**
This PR is to make RawMessageDelivery option configurable.

Related to #1597

### CODE REVIEW

**Comment by honkuan86** [comment]
Hi @iancooper , I have made a initial changes for making the RawMessageDelivery configurable. 

I have a question that need your advice, the current implementation does not verify the RawMessageDelivery setting against Aws Sns, so when both of the settings are not consistent (true at Sns, false at local) then exception may occur. 

Do we need to verify the setting during startup ?

**Comment by iancooper** [comment]
Thanks @honkuan86 I'll try to review this in the next day or so

**Comment by iancooper** [comment]
Sorry @honkuan86 I was out last week, I'll prioritize this week

**Comment by honkuan86** [comment]
Hi @iancooper , any chance you can review this PR next week ?

**Comment by iancooper** [comment]
@honkuan86 Almost on top of the Scope issues, then I can get to this one

**Review by iancooper — APPROVED** [review]
Sorry this took so long. It looks good, probably easiest to merge and make sure everything still works. But this is what we asked for, so awesome job

**Pull request merged**
