### PR TITLE
AWSSQS Fixes

### PR DESCRIPTION
**Pull request by slang25**
Hi @iancooper, following our chat in the JustSaying repo, I had a quick review of the code here and spotted a couple of little fixes.

### CODE REVIEW

**Comment by iancooper** [comment]
Thanks. missed this one amidst other priorities

**Comment by slang25** [comment]
@iancooper no worries. Did you mean to close this?

**Comment by iancooper** [comment]
Did I not merge first?

Ian Cooper 07970-411892 (M) 
ian.hammond.cooper (Skype) 

    On Sunday, 4 August 2019, 15:34:49 BST, Stuart Lang <notifications@github.com> wrote:  
 
 
@iancooper no worries. Did you mean to close this?

**Comment by iancooper** [comment]
OK, I merged. We are in a parlous state whilst we try and get some Db store fixes in for checking some builds right now

**Pull request merged**
