### PR TITLE
Kafka message header builder implementation

### PR DESCRIPTION
**Pull request by honkuan86**
This PR include changes to allow custom implementation of a Kafka message header builder. The current implementation does not allowed to customize the header key and values before sending to a Kafka topic. This changes should allow customization of the message header such as camelCasing.

Related issue: #2402

### CODE REVIEW

**Comment by iancooper** [comment]
Hi @honkuan86,

I just wanted to understand intent here. The goal is to enable you to customize how the headers are produced. But at first glance it seems that to do that you offer the facility to inject a whole new class to build headers. That seems as though it is putting a lot of work on the implementer, if their goal is to simply shift to camel casing.

Another option would be a set of configuration options that you can pass in (think of the way you can customize System.Text.Json's json serializer by using JsonSerializerOptions: https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/configure-options?pivots=dotnet-7-0)

Is there a particular reason your design went down this path?

**Comment by honkuan86** [comment]
hi @iancooper ,

Yes, apart from changing to camel case, we also want to have a different value on the timestamp, which is a ISO8601 compliant format timestamp, the default one is a unix timestamp, so I think by providing an option for the implementer to customize the way to build the header would be flexible. 

But I think most people would just go for the default one, only those who has a needs to customize the headers they'll have the option to fully customize it.

**Comment by iancooper** [comment]
@honkuan86 Understood. I'll merge. We may return to it at some point, if we think that configuration might be a better way to handle it, but let's fix the problem for you for now

**Review by iancooper — APPROVED** [review]

**Comment by iancooper** [comment]
@honkuan86 Do you feel up to adding some information on this to the Docs repo? I'll check in on the other maintainers and what we have scheduled to determine next available release

**Comment by iancooper** [comment]
@honkuan86 Out in 9.4.0, sorry for the delay

**Pull request merged**
