### PR TITLE
Add Structured Logging #1254

### PR DESCRIPTION
**Pull request by preardon**
I have tired to Align the Logging Keys the best I can, I have a list of keys that I can provide a list of these if required

### CODE REVIEW

**Comment by holytshirt** [comment]
Nice! Thank you for fixing the interpolated string to template strings! Helps with perf!
Still going through it. 
Was wondering if we should differentiate `Id`  to `CommandId`, `EventId`, `MessageId` in the areas where we can?
@iancooper @preardon

**Comment by preardon** [comment]
@holytshirt I believe I'm Always using Id for MessageID, as From memory there are no Id's just Types, Unless you are talking about the MessageId for that Type

Event and Command are in CommandType and EventType, I was wondering if should make them Type

**Comment by iancooper** [comment]
There is a "Request Id" which could be event or command derived type,  and a "Message Id" for what goes over the wire.

**Comment by iancooper** [comment]
@preardon I labeled this as "in  progress" as it seemed we had some change. If we are done, just change the label, and we can look to merge.

**Comment by preardon** [comment]
@iancooper If yourself and @holytshirt Are happy with what I've done, I'm happy to have this merged in However I can't see how to add/Delete a Tag. I will do a rebase now

**Review by iancooper — APPROVED** [review]
Alright, let's take this in, better to get it out and tested and improve from there than sit on it

**Comment by iancooper** [comment]
@preardon I'll see if I can run these one at a time to try and get them  to pass in GA

**Comment by iancooper** [comment]
@preardon I've tried lengthening the timeout window. It's GFA not us, as the tests pass in 15.7s locally. If it gets painful enough, then if you can get green locally I'll merge

**Comment by iancooper** [comment]
Alright @preardon If you tell me it's green, I'll merge and test locally :-)

**Comment by preardon** [comment]
@iancooper I just rebased and fixed the conflict on the contributors.md, They Just Ran in the Pipeline, I'm not on one of my Normal Dev Machines But I'll try to run them here as well, I don't expect to see any of them fail due to the nature of the change but I'll try to do another run locally

**Comment by preardon** [comment]
@iancooper Core.Test all Green 151 Passed, 3 Skipped, 0 Failed

**Comment by iancooper** [comment]
Cool, I might not merge before tomorrow now. But it's good to go.

**Comment by preardon** [comment]
Not a problem mate, I no rush, just happy to get this into v9, I was hoping to look into the obfuscation pieces as well but we'll see what I can manage

**Comment by iancooper** [comment]
@preardon Merged. We just need to get @holytshirt to release at some point. @holytshirt, it would be nice to get publisher confirms reviewed and merged as part of that release

**Pull request merged**
