### PR TITLE
Create dotnetcore.yml for actions

### PR DESCRIPTION
**Pull request by holytshirt**

### CODE REVIEW

**Comment by iancooper** [comment]
@holytshirt I don't really know enough about actions to review this. Can @DevJonny help? If not, just use admin rights to push

**Comment by holytshirt** [comment]
@iancooper still playing with this, don't merge yet

**Comment by iancooper** [comment]
Assuming this is still WIP @holytshirt

**Comment by iancooper** [comment]
Closed the PR. Looking at this again, and using the material on this branch to figure out how to do it

**Pull request closed without merging**
