### PR TITLE
fix(SeviceActivator): Logs unhandled exceptions in handlers as error …

### PR DESCRIPTION
**Pull request by holytshirt**
…on publishasync (#2757)

### CODE REVIEW

**Comment by holytshirt** [comment]
I in-lined the method as it was hard to compare and think about the exception handling for a Exception and AggregateException

**Review by iancooper — APPROVED** [review]
Looks good. I don't think the handling of aggregate exceptions is so long that we need to necessarily wonder about inlining. I do wonder if at some point we should look at commonality though between individual vs aggregate and factor out the action as a method. Not for now though.

**Comment by holytshirt** [comment]
> handling

It used to be in it's own method, I took out it's method and put it in place. I think that is why the logging was missing as it was hard to reason that the aggregate exception and normal exception should be similar

**Comment by holytshirt** [comment]
I managed to get the logging tests working and now covered by tests. Renamed the requeue ones to what it is testing.

**Pull request merged**
