### PR TITLE
remove some redundant whitespace

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Review by iancooper — APPROVED** [review]

**Comment by iancooper** [comment]
Thanks @SimonCropp. I am hoping you did this because a tool offered to remove it, and you didn't have to pore over all our files by hand, which would have been a heroic effort.

**Comment by SimonCropp** [comment]
@iancooper the majority was automated. but my tooling doesnt seem to handle the side of this solution very well. so it took a few passes

**Comment by SimonCropp** [comment]
done with this one

**Comment by iancooper** [comment]
Cool, and thanks very much for taking this on. It can be worth using the "Mark as Draft" if you have an ongoing PR you want us to hold off reviewing until it's done.

**Comment by SimonCropp** [comment]
noted

**Comment by SimonCropp** [comment]
BTW my other current PRs a ready to go if u r happy.

i will mark future ones as draft until they are ready

**Review by iancooper — APPROVED** [review]

**Comment by iancooper** [comment]
@SimonCropp Do you want to have a look at the build errors. It's worth noting we build against netstandard2.0 as well as net6/7 and we have to use C#8 mostly as a result. Tools may get this wrong.

**Comment by SimonCropp** [comment]
yep. i will move this back to draft and resolve the build errors

**Comment by iancooper** [comment]
PS @SimonCropp Thanks for all the PRs doing cleanup; it is appreciated.

**Comment by SimonCropp** [comment]
going to close this . and instead split it over several prs

**Pull request closed without merging**
