### PR TITLE
remove redundant langversion

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Review by iancooper — COMMENTED** [review]
I'm cautious on this one. As we are netstandard2.0 (not in sample projects) we are technically 7.3, although 8 works in some circumstances (really that is 2.1 but some features are safe). If we use a higher version there may not be a backfill for that feature.

Any thoughts on intent here?

**Comment by SimonCropp** [comment]
netstandard works fine with all newer c# versions. there a just a few features u cant use. And if  accidentally use those features, you will get a compile error

**Comment by SimonCropp** [comment]
and for the majority of "no supported" c#+runtime features you can polyfill them https://github.com/SimonCropp/Polyfill

**Comment by SimonCropp** [comment]
the broken build seems unrelated to this change?

```
(node:[18](https://github.com/BrighterCommand/Brighter/actions/runs/4617958656/jobs/8164875343?pr=2600#step:5:19)02) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in [20](https://github.com/BrighterCommand/Brighter/actions/runs/4617958656/jobs/8164875343?pr=2600#step:5:21)23.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers
```

**Comment by iancooper** [comment]
@SimonCropp You can ignore aws-ci errors which are timing related on GitHub, unless you are specifically working on that transport.

**Pull request closed without merging**
