### PR TITLE
Enable a Blocking Sweep

### PR DESCRIPTION
**Pull request by preardon**
Allow the sweeper to run a sweep on the foreground thread so that the locking provider can work

#3321

### CODE REVIEW

**Comment by preardon** [comment]
@iancooper let me know your thoughts, this loosely follows what we did for v9

**Comment by iancooper** [comment]
I guess that I should ask the dumb question. Why does the locking provider fail on a background thread? It would seem that the a ClearOutboxAsync ought not to block,  by it's name. That either means it is able to call async directly (which might not need a Thread Run, or can't, in which case we should wrap it in a Thread Run?

What am I missing?

**Comment by preardon** [comment]
The problem is that the Locking provider has no visibility to the background thread is it unlocks when this method returns which has no bearing on the background thread at all (as its kicked off on another thread) the Locking provider is pointless using this without a blocking call. The way I see it we have 4 options

1. Throw away the Locking Provider (I don't suggest this as it was brought in to solve the multi Farm Problem)
2. Move the Locking Provider into the core - We can do this but also not necessary
3. The Solution I've put forward here where we can pick if this call blocks or not
4. Make this call always Blocking, the call is only used by the Sweeper (up and down the stack) and given the sweeper now has a locking provider it in I would imagine if we make the change I've made so far then it would never be run in the background.  As an addition to this we could move this out of the Command Processor all together and just pass a `OutboxProducerMediator` to the sweeper, this wouldn't get around us needing to make it run blocking.

I don't hate the idea of the things done in option 4 as it feels a little cleaner, but if we wanted to maintain existing functionality we would need 3.

Let me know your thoughts @iancooper

**Comment by iancooper** [comment]
> The problem is that the Locking provider has no visibility to the background thread is it unlocks when this method returns which has no bearing on the background thread at all (as its kicked off on another thread) the Locking provider is pointless using this without a blocking call. 

Still a little puzzled. Where am I am I missing something?

- I start a TimedSweeper; it starts a timer that runs a sweep at an interval, it runs on the thread pool
- Once signaled, the thread pool thread running sweep tries to obtain a lock; it ought to use a unique name, but I notice TimedOutboxSweeper hardcodes this? Is that right. Should it be passed in, or just a GUID? That way multiple threads all have a unique Id.
- If it is an in-process lock, it is a semaphore slim, which is process wide (has to be for producer-consumer usage); if it is a distributed lock then it is not impacted by thread affinity either, surely. Isn't it always match id to table and release

I think I am still missing a part of this puzzle. Or perhaps it is just that we don't generate a unique sweeper name?

>The way I see it we have 4 options

>  As an addition to this we could move this out of the Command Processor all together and just pass a `OutboxProducerMediator` to the sweeper, this wouldn't get around us needing to make it run blocking.

I don't hate the idea of the Sweeper calling the OutboxProducerMediator directly, regardless of the misunderstanding here, as routing through the CommandProcessor might be waste

**Review by iancooper — APPROVED** [review]

**Pull request merged**
