### PR TITLE
Fix some issues with AWS (failing tests and TopicARN validation)

### PR DESCRIPTION
**Pull request by iancooper**

### CODE REVIEW

**Comment by iancooper** [comment]
WiP as I need to add a test around the TopicArn stuff

**Comment by iancooper** [comment]
It's possible that this one, I accidentally branched from, Kakfa. So I have left this as a draft behind that commit as it is fixes only

**Comment by holytshirt** [comment]
> It's possible that this one, I accidentally branched from, Kakfa. So I have left this as a draft behind that commit as it is fixes only

Yes you did

**Comment by iancooper** [comment]
It also seems to possess whatever screw up adding those env variables to connect to Confluent creates for the Kafka tests

**Pull request merged**
